# Generated by Django 3.2.11 on 2022-02-19 02:28

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('houmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='houmer',
            options={'verbose_name': 'Houmer', 'verbose_name_plural': 'Houmer'},
        ),
        migrations.AlterField(
            model_name='scheduledvisit',
            name='status',
            field=django_fsm.FSMField(choices=[('SCHEDULED', 'Scheduled'), ('IN_TRANSIT', 'In transit'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
    ]
