# Generated by Django 3.2.11 on 2022-02-19 17:13

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('houmer', '0002_auto_20220219_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledvisit',
            name='status',
            field=django_fsm.FSMField(choices=[('SCHEDULED', 'Scheduled'), ('IN_TRANSIT', 'In transit'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20, protected=True),
        ),
    ]
