# Generated by Django 3.2.11 on 2022-02-21 05:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('houmer', '0003_alter_scheduledvisit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledvisitevent',
            name='time_at',
        ),
        migrations.AddField(
            model_name='scheduledvisitevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
