# Generated by Django 3.2.11 on 2022-02-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houmer', '0006_scheduledvisitstatistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledvisitstatistic',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
