# Generated by Django 3.2.11 on 2022-02-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houmer', '0007_scheduledvisitstatistic_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledvisitstatistic',
            name='stay_time_in_minutes',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scheduledvisitstatistic',
            name='velocity_km_x_h',
            field=models.BigIntegerField(null=True),
        ),
    ]
